author = "Steinn Eldjárn Sigurðarson"
description = "Lakkrís is a small black and white theme for Hugo."
license = "MIT"
name = "lakkris"
source_repo = "https://github.com/steinnes/lakkris"
tags = ["", ""]
